# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GuideInteractifDialog
                                 A QGIS plugin
 aide interactive pour l'ONF
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-06
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Robin FICHT
        email                : robin.ficht@onf.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import (QDialog, QVBoxLayout, QHBoxLayout, QLabel,
                                  QPushButton, QListWidget, QTextEdit,
                                  QProgressBar, QFrame, QSizePolicy, QMessageBox)
from qgis.PyQt.QtGui import QFont

from .guides_predefined import get_all_guides


class GuideInteractifDialog(QDialog):
    def __init__(self, iface, parent=None):
        """Constructor."""
        super(GuideInteractifDialog, self).__init__(parent)
        self.iface = iface
        self.current_guide = None
        self.available_guides = get_all_guides()
        
        self.setup_ui()
    
    def setup_ui(self):
        """Configure l'interface utilisateur"""
        self.setWindowTitle("Guide Interactif QGIS")
        self.resize(600, 500)
        
        main_layout = QVBoxLayout()
        
        # Titre
        title_label = QLabel("Guide Interactif ONF")
        title_font = QFont()
        title_font.setPointSize(16)
        title_font.setBold(True)
        title_label.setFont(title_font)
        title_label.setAlignment(Qt.AlignCenter)
        main_layout.addWidget(title_label)
        
        # Liste des guides disponibles
        guides_label = QLabel("Sélectionnez un guide :")
        main_layout.addWidget(guides_label)
        
        self.guides_list = QListWidget()
        for guide in self.available_guides:
            self.guides_list.addItem(f"📖 {guide.name}")
        self.guides_list.currentRowChanged.connect(self.on_guide_selected)
        main_layout.addWidget(self.guides_list)
        
        # Description du guide
        self.guide_description = QLabel("")
        self.guide_description.setWordWrap(True)
        self.guide_description.setStyleSheet("QLabel { padding: 10px; background-color: #f0f0f0; border-radius: 5px; }")
        main_layout.addWidget(self.guide_description)
        
        # Séparateur
        line = QFrame()
        line.setFrameShape(QFrame.HLine)
        line.setFrameShadow(QFrame.Sunken)
        main_layout.addWidget(line)
        
        # Zone d'affichage de l'étape actuelle
        step_label = QLabel("Étape en cours :")
        main_layout.addWidget(step_label)
        
        self.step_title = QLabel("Sélectionnez un guide pour commencer")
        step_title_font = QFont()
        step_title_font.setPointSize(12)
        step_title_font.setBold(True)
        self.step_title.setFont(step_title_font)
        self.step_title.setStyleSheet("QLabel { color: #2c3e50; }")
        main_layout.addWidget(self.step_title)
        
        self.step_description = QTextEdit()
        self.step_description.setReadOnly(True)
        self.step_description.setMaximumHeight(150)
        self.step_description.setText("Choisissez un guide dans la liste ci-dessus pour commencer.")
        main_layout.addWidget(self.step_description)
        
        # Barre de progression
        self.progress_bar = QProgressBar()
        self.progress_bar.setVisible(False)
        main_layout.addWidget(self.progress_bar)
        
        # Boutons de navigation
        button_layout = QHBoxLayout()
        
        self.btn_start = QPushButton("▶ Démarrer le guide")
        self.btn_start.setEnabled(False)
        self.btn_start.clicked.connect(self.start_guide)
        self.btn_start.setStyleSheet("QPushButton { background-color: #27ae60; color: white; font-weight: bold; padding: 8px; }")
        button_layout.addWidget(self.btn_start)
        
        self.btn_previous = QPushButton("◀ Précédent")
        self.btn_previous.setVisible(False)
        self.btn_previous.clicked.connect(self.previous_step)
        button_layout.addWidget(self.btn_previous)
        
        self.btn_next = QPushButton("Suivant ▶")
        self.btn_next.setVisible(False)
        self.btn_next.clicked.connect(self.next_step)
        self.btn_next.setStyleSheet("QPushButton { background-color: #3498db; color: white; font-weight: bold; padding: 8px; }")
        button_layout.addWidget(self.btn_next)
        
        self.btn_highlight = QPushButton("💡 Afficher l'élément")
        self.btn_highlight.setVisible(False)
        self.btn_highlight.clicked.connect(self.show_highlight)
        self.btn_highlight.setStyleSheet("QPushButton { background-color: #f39c12; color: white; font-weight: bold; padding: 8px; }")
        button_layout.addWidget(self.btn_highlight)
        
        self.btn_close = QPushButton("Fermer")
        self.btn_close.clicked.connect(self.close)
        button_layout.addWidget(self.btn_close)
        
        main_layout.addLayout(button_layout)
        
        self.setLayout(main_layout)
    
    def on_guide_selected(self, index):
        """Appelé quand un guide est sélectionné"""
        if index >= 0:
            guide = self.available_guides[index]
            self.guide_description.setText(f"<b>{guide.name}</b><br>{guide.description}")
            self.btn_start.setEnabled(True)
    
    def start_guide(self):
        """Démarre le guide sélectionné"""
        index = self.guides_list.currentRow()
        if index >= 0:
            self.current_guide = self.available_guides[index]
            self.current_guide.reset()
            
            # Cacher la liste des guides et afficher les contrôles
            self.guides_list.setVisible(False)
            self.guide_description.setVisible(False)
            self.btn_start.setVisible(False)
            
            self.btn_previous.setVisible(True)
            self.btn_next.setVisible(True)
            self.btn_highlight.setVisible(True)
            self.progress_bar.setVisible(True)
            
            # Afficher la première étape
            self.update_step_display()
    
    def next_step(self):
        """Passe à l'étape suivante"""
        if self.current_guide:
            self.current_guide.next_step()
            
            if self.current_guide.is_finished():
                self.finish_guide()
            else:
                self.update_step_display()
    
    def previous_step(self):
        """Retourne à l'étape précédente"""
        if self.current_guide:
            self.current_guide.previous_step()
            self.update_step_display()

    def _set_previous_button_action(self, text, callback):
        """Configure le bouton de gauche (texte + action) de facon robuste."""
        self.btn_previous.setText(text)
        try:
            self.btn_previous.clicked.disconnect()
        except TypeError:
            # Aucune connexion active
            pass
        self.btn_previous.clicked.connect(callback)
    
    def show_highlight(self):
        """Affiche la mise en évidence de l'élément"""
        if self.current_guide:
            step = self.current_guide.get_current_step()
            if step:
                if not step.has_target():
                    QMessageBox.information(
                        self,
                        "Guide Interactif",
                        "Cette etape n'a pas d'element cible a surligner."
                    )
                    return

                highlighted = step.show_highlight(self.iface)
                if not highlighted:
                    QMessageBox.warning(
                        self,
                        "Guide Interactif",
                        "Impossible de trouver cet element dans l'interface QGIS. "
                        "Essayez apres avoir ouvert le menu/fenetre indique(e)."
                    )
    
    def update_step_display(self):
        """Met à jour l'affichage avec l'étape actuelle"""
        if not self.current_guide:
            return
        
        step = self.current_guide.get_current_step()
        if step:
            self.step_title.setText(step.title)
            self.step_description.setText(step.description)
            
            # Mettre à jour la barre de progression
            current, total = self.current_guide.get_progress()
            self.progress_bar.setMaximum(total)
            self.progress_bar.setValue(current + 1)
            self.progress_bar.setFormat(f"Étape {current + 1} sur {total}")

            # A la premiere etape, proposer une sortie explicite du guide.
            if current == 0:
                self._set_previous_button_action("← Retour aux guides", self.return_to_guide_list)
                self.btn_previous.setEnabled(True)
            else:
                self._set_previous_button_action("◀ Précédent", self.previous_step)
                self.btn_previous.setEnabled(True)

            self.btn_highlight.setEnabled(step.has_target())
    
    def finish_guide(self):
        """Appelé quand le guide est terminé"""
        self.step_title.setText("✅ Guide terminé !")
        self.step_description.setText(
            f"<b>Félicitations !</b><br><br>"
            f"Vous avez terminé le guide '{self.current_guide.name}'.<br><br>"
            f"Vous pouvez fermer cette fenêtre ou sélectionner un autre guide."
        )
        
        self.btn_next.setVisible(False)
        self.btn_highlight.setVisible(False)
        self.btn_previous.setVisible(False)
        
        # Afficher un bouton pour revenir à la liste
        self.btn_start.setText("← Retour aux guides")
        self.btn_start.setVisible(True)
        self.btn_start.clicked.disconnect()
        self.btn_start.clicked.connect(self.return_to_guide_list)
    
    def return_to_guide_list(self):
        """Retourne à la liste des guides"""
        # Nettoyer
        if self.current_guide:
            step = self.current_guide.get_current_step()
            if step:
                step.hide_highlight()
        
        # Réinitialiser l'interface
        self.guides_list.setVisible(True)
        self.guide_description.setVisible(True)
        self.progress_bar.setVisible(False)
        
        self.btn_start.setText("▶ Démarrer le guide")
        self.btn_start.clicked.disconnect()
        self.btn_start.clicked.connect(self.start_guide)
        self.btn_start.setVisible(True)
        self.btn_start.setEnabled(False)  # Sera activé à la sélection d'un guide

        self._set_previous_button_action("◀ Précédent", self.previous_step)
        
        self.btn_previous.setVisible(False)
        self.btn_next.setVisible(False)
        self.btn_highlight.setVisible(False)
        
        self.step_title.setText("Sélectionnez un guide pour commencer")
        self.step_description.setText("Choisissez un guide dans la liste ci-dessus pour commencer.")
        
        self.current_guide = None
    
    def closeEvent(self, event):
        """Appelé quand la fenêtre est fermée"""
        # Nettoyer les highlights
        if self.current_guide:
            step = self.current_guide.get_current_step()
            if step:
                step.hide_highlight()
        
        super().closeEvent(event)
